Part 4
ineedjet/qna pull request #2
Opened 2017-08-17 22:15 UTC by ineedjet

2017-08-18 11:02 UTC, vkurennov requested changes

2017-08-18 11:02 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect { post :create, params: { question_id: question.id, answer: attributes_for(:answer) } }.to change(Answer, :count).by(1)
Тут надо проверить, что овтет связывается с вопросом. Можно прямо в change через ассоциации вопроса

2017-08-18 18:24 UTC, darialapina commented on app/controllers/answers_controller.rb
> +    @answer.question = @question
Связанные объекты лучше создавать через ассоциации: @question.answers.new(answer_params)

2017-08-18 21:48 UTC, ineedjet commented on app/controllers/answers_controller.rb
> +    @answer.question = @question
класс, спасибо =)

2017-08-19 08:45 UTC, vkurennov approved these changes

2017-08-19 09:20 UTC, merged